//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RulUfimtsev.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int OrderID { get; set; }
        public int OrderStatus { get; set; }
        public System.DateTime OrderDeliveryDate { get; set; }
        public int OrderPickupPoint { get; set; }
        public System.DateTime OrderDate { get; set; }
        public string CurrentFullName { get; set; }
        public int ReceiptCode { get; set; }
    
        public virtual PickupPoint PickupPoint { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }

        public double Cost { get; set; }

        public string OrStatus
        {
            get
            {
                if(OrderStatus == 1)
                {
                    return "Новый";
                }
                else
                {
                    return "Завершен";
                }
                
            }
        }
        public double CostWithDiscount { get; set; }
        public string CostString { get; set; }
        public string CostWithDiscountString { get; set; }
        public string ProductList { get; set; }
        
        public string DeliveryDate
        {
            get
            {
                return OrderDeliveryDate.ToString("D");
            }
        }
        
        public List<Product> productList { get; set; }
    }
}
